#!/usr/bin/env bash
# =============================================================================
# rollback.sh — records how to undo any state-changing action.
#
# Design: this tool is read-only by default, so most runs record nothing. When
# an action DOES change system state (e.g. --fix restarts a service or resubmits
# a certificate), it MUST call rollback_record() BEFORE acting, passing a shell
# command that restores the previous state. Those commands are appended to a
# per-run, executable rollback journal so an operator can review and, if needed,
# run it to revert.
# =============================================================================

ROLLBACK_FILE=""
ROLLBACK_COUNT=0

# init_rollback LOG_DIR
init_rollback() {
    local log_dir="$1/rollback"
    mkdir -p "$log_dir" 2>/dev/null || {
        log ERROR "Cannot create rollback directory: $log_dir"
        return 1
    }
    local ts; ts="$(date +%Y%m%d-%H%M%S)"
    ROLLBACK_FILE="${log_dir}/rollback-${ts}.sh"
    {
        echo "#!/usr/bin/env bash"
        echo "# Rollback journal generated by freeipa-quick-manager"
        echo "# Run started: $(date '+%Y-%m-%d %H:%M:%S %Z') on $(hostname -f 2>/dev/null || hostname)"
        echo "#"
        echo "# Each block below reverts one state-changing action taken in this run,"
        echo "# in the order they occurred. Review carefully, then execute the ones you"
        echo "# need. Actions are listed newest-last."
        echo "set -euo pipefail"
        echo ""
    } > "$ROLLBACK_FILE"
    chmod +x "$ROLLBACK_FILE" 2>/dev/null || true
    log INFO "Rollback journal: ${ROLLBACK_FILE}"
}

# rollback_record "human description" "restore command"
# Call this immediately BEFORE performing a mutating action.
rollback_record() {
    local description="$1" restore_cmd="$2"
    [[ -z "$ROLLBACK_FILE" ]] && { log ERROR "rollback_record called before init_rollback"; return 1; }
    ROLLBACK_COUNT=$((ROLLBACK_COUNT + 1))
    {
        echo "# --- [$ROLLBACK_COUNT] $(date '+%Y-%m-%d %H:%M:%S') -------------------------------"
        echo "# Action: ${description}"
        echo "${restore_cmd}"
        echo ""
    } >> "$ROLLBACK_FILE"
    log INFO "Rollback recorded (#$ROLLBACK_COUNT): ${description}"
}

# Called at the end of the run to note whether any rollback steps exist.
finalize_rollback() {
    [[ -z "$ROLLBACK_FILE" ]] && return 0
    if (( ROLLBACK_COUNT == 0 )); then
        echo "# No state-changing actions were taken during this run (read-only)." >> "$ROLLBACK_FILE"
        log INFO "No mutating actions taken; rollback journal is empty."
    else
        log INFO "Rollback journal contains ${ROLLBACK_COUNT} step(s): ${ROLLBACK_FILE}"
    fi
}
